check file size, redundant pre-commit

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -28,7 +28,7 @@ jobs:
 
       - name: Extra wait
         run: |
-          sleep 10
+          sleep 30
 
       - name: Health check
         run: |
@@ -43,6 +43,11 @@ jobs:
           # check if the slr_results.zip file exists, error if not
           if [ ! -f ./tests/slr_results.zip ]; then
             echo "Error: slr_results.zip not found!"
+            exit 1
+          fi
+          # check the size of the file, should be > 10kb
+          if [ $(stat -c%s "./tests/slr_results.zip") -le 10240 ]; then
+            echo "Error: slr_results.zip is less than 10kb!"
             exit 1
           fi
           echo "slr_results.zip file exists, proceeding with next steps."
